### ISSUE TITLE
Saving attachment to file fails

### ISSUE THREAD

**Issue by madzhuga** [aquasync/ruby-msg#14]
Hi! I am trying to save message attachment to a file (to process it than):

msg.attachments.first.save(new_file)
NoMethodError: undefined method `each_read' for #<Ole::Storage::RangesIOMigrateable:0x0055729e85b040>
from ..gems/2.3.0/gems/ruby-msg-1.5.2/lib/mapi/base.rb:33:in `save'

**Comment by aquasync** [comment]
Ah, looks like that's been broken for a while. There was a `RangesIO#each_read` function back when the ole code got split out as ruby-ole in early 2007, and it was removed in a cleanup later that year! Oops. Was just a 1-line function - I'll fix save.

**Comment by madzhuga** [comment]
Thanks! Are you going to publish new gem version? (Otherwise I can just use master branch)

**Comment by FranklinYu** [comment]
Any news? Will this be released to RubyGems?

**Comment by aquasync** [comment]
Ok have finally released with that fix - 10 years after last version! Hopefully that works...
