### ISSUE TITLE
Homepage on rubygems.org

### ISSUE THREAD

**Issue by mcarpenter** [aquasync/ruby-msg#18]
Hi,

The homepage for this gem at [rubygems.org](https://rubygems.org/gems/ruby-msg) points to a deprecated Google Code repo instead of here. Can you please update it? (I just hit #15 and didn't know where to find help).

Thanks.

**Comment by aquasync** [comment]
Fair enough. Not actually sure how to change it, but I guess it works from the gem metadata so will update after a new release as that has already been changed.

**Comment by aquasync** [comment]
Hmm, I've pushed a new release which has github as the homepage, but the link didn't change. Maybe it takes a while to refresh? I can't find any way to edit, but if you know how please let me know.

**Comment by mcarpenter** [comment]
I see your update in the gemspec, and I checked there is no other mention of "code.google" in the repo yet the old homepage pesists at rubygems.org.

I checked by API (`GET https://rubygems.org/api/v1/gems/ruby-msg.json`) and it is also in the response:


```json
{
  "name": "ruby-msg",
  "downloads": 760428,
  "version": "1.5.3",
  ...
  "homepage_uri": "http://code.google.com/p/ruby-msg",
  ...
}
```

This lead me to [gemspec metadata](https://guides.rubygems.org/specification-reference/#metadata) which was new for rubygems 2.0. I think you need to add that section to the gemspec to make the change to the homepage URI in the web UI:

```ruby
s.metadata = {
  "bug_tracker_uri"   => "https://example.com/user/bestgemever/issues",
  "changelog_uri"     => "https://example.com/user/bestgemever/CHANGELOG.md",
  "documentation_uri" => "https://www.example.info/gems/bestgemever/0.0.1",
  "homepage_uri"      => "https://bestgemever.example.io",
  "mailing_list_uri"  => "https://groups.example.com/bestgemever",
  "source_code_uri"   => "https://example.com/user/bestgemever",
  "wiki_uri"          => "https://example.com/user/bestgemever/wiki"
  "funding_uri"       => "https://example.com/donate"
}
```

**Comment by aquasync** [comment]
Interesting. Looks like `s.homepage` is still documented, and it seems wrong for it to be using stale data instead. Anyway will try duplicating it into metadata to see if that helps.

**Comment by aquasync** [comment]
Yep that seems to have done it - thanks for the pointer.
