### ISSUE TITLE
Is this repository the successor of ruby-msg on Google Code?

### ISSUE THREAD

**Issue by blueicehaller** [aquasync/ruby-msg#21]
Hi,
I was not able to find information about if this repository is the successor of ruby-msg on Google Code?
- https://code.google.com/archive/p/ruby-msg/wikis/Home.wiki
- https://code.google.com/archive/p/ruby-msg/downloads

Thank you in advance.

**Comment by aquasync** [comment]
Yes that's right.

**Comment by aquasync** [comment]
Switched from svn to git in 2009 and mirrored to googlecode, GitHub and rubyforge, and eventually the other two died...

**Comment by aquasync** [comment]
Only way to run it at the moment is to install ruby and then the gem via the gem package manager.
